function C = importFile2CellArray( filename, n )
%IMPORTFILE2CELLARRAY 
% Imports a comma delimmited file with up to 35 columns as a cell array

%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/jaywellik/Documents/JMADATA/enbo/V200801.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/01/05 10:00:53

if nargin==2

   error('This function does not take variable input arguments yet. This function will import up to 35 columns.')
    
end
   
%% Initialize variables.
delimiter = ',';

%% Format for each line of text:
% For more information, see the TEXTSCAN documentation.
formatSpec = [repmat('%q',1,35) '%[^\n\r]'];

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
VarName1 = dataArray{:, 1};
VarName2 = dataArray{:, 2};
VarName3 = dataArray{:, 3};
VarName4 = dataArray{:, 4};
VarName5 = dataArray{:, 5};
VarName6 = dataArray{:, 6};
VarName7 = dataArray{:, 7};
VarName8 = dataArray{:, 8};
VarName9 = dataArray{:, 9};
VarName10 = dataArray{:, 10};
VarName11 = dataArray{:, 11};
VarName12 = dataArray{:, 12};
VarName13 = dataArray{:, 13};
VarName14 = dataArray{:, 14};
VarName15 = dataArray{:, 15};
VarName16 = dataArray{:, 16};
VarName17 = dataArray{:, 17};
VarName18 = dataArray{:, 18};
VarName19 = dataArray{:, 19};
VarName20 = dataArray{:, 20};
VarName21 = dataArray{:, 21};
VarName22 = dataArray{:, 22};
VarName23 = dataArray{:, 23};
VarName24 = dataArray{:, 24};
VarName25 = dataArray{:, 25};
VarName26 = dataArray{:, 26};
VarName27 = dataArray{:, 27};
VarName28 = dataArray{:, 28};
VarName29 = dataArray{:, 29};
VarName30 = dataArray{:, 30};
VarName31 = dataArray{:, 31};
VarName32 = dataArray{:, 32};
VarName33 = dataArray{:, 33};
VarName34 = dataArray{:, 34};
VarName35 = dataArray{:, 35};
C = [VarName1 VarName2 VarName3 VarName4 VarName5, ...
    VarName6 VarName7 VarName8 VarName9 VarName10, ...
    VarName11 VarName12 VarName13 VarName14 VarName15, ...
    VarName16 VarName17 VarName18 VarName19 VarName20, ...
    VarName21 VarName22 VarName23 VarName24 VarName25, ...
    VarName26 VarName27 VarName28 VarName29 VarName30, ...
    VarName31 VarName32 VarName33 VarName34 VarName35];
