function [catalog] = import1IGNfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [EVENTO,FECHA,HORA,LATITUD,LONGITUD,PROFKM,INTEN,MAG,TIPOMAG,LOCALIZACIN]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [EVENTO,FECHA,HORA,LATITUD,LONGITUD,PROFKM,INTEN,MAG,TIPOMAG,LOCALIZACIN]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [Evento,Fecha,Hora,Latitud,Longitud,ProfKm,Inten,Mag,TipoMag,Localizacin] = importfile('catalogoComunSV_1521067144091.csv',2, 119728);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/03/14 15:41:11

%% Initialize variables.
delimiter = ';';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,4,5]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

% Convert the contents of columns with dates to MATLAB datetimes using date
% format string.
try
    dates{3} = datetime(dataArray{3}, 'Format', 'HH:mm:ss', 'InputFormat', 'HH:mm:ss');
catch
    try
        % Handle dates surrounded by quotes
        dataArray{3} = cellfun(@(x) x(2:end-1), dataArray{3}, 'UniformOutput', false);
        dates{3} = datetime(dataArray{3}, 'Format', 'HH:mm:ss', 'InputFormat', 'HH:mm:ss');
    catch
        dates{3} = repmat(datetime([NaN NaN NaN]), size(dataArray{3}));
    end
end

anyBlankDates = cellfun(@isempty, dataArray{3});
anyInvalidDates = isnan(dates{3}.Hour) - anyBlankDates;
dates = dates(:,3);

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [1,4,5]);
rawCellColumns = raw(:, [2,6,7,8,9,10]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
Evento = cell2mat(rawNumericColumns(:, 1));
Fecha = rawCellColumns(:, 1);
Hora = dates{:, 1};
Latitud = cell2mat(rawNumericColumns(:, 2));
Longitud = cell2mat(rawNumericColumns(:, 3));
ProfKm = rawCellColumns(:, 2);
Inten = rawCellColumns(:, 3);
Mag = rawCellColumns(:, 4);
TipoMag = rawCellColumns(:, 5);
Localizacin = rawCellColumns(:, 6);

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% Hora=datenum(Hora);

parfor i=1:numel(Evento)
    
    dts(i) = datenum(sprintf('%s %s',Fecha{i},Hora(i)),'dd/mm/yyyy HH:MM:SS');
        
    catalog(i).Latitude = Latitud(i);
    catalog(i).Longitude = Longitud(i);
    if cellfun('isempty',ProfKm(i))
        catalog(i).Depth = nan;
    else
        catalog(i).Depth = str2num(ProfKm{i});
    end
    if cellfun('isempty',Mag(i))
        catalog(i).Magnitude = nan;
%         catalog(i).TypeMag = [];
    else
        catalog(i).Magnitude = str2num(Mag{i});
        catalog(i).TypeMag = TipoMag{i};
    end    
    
%     catalog(i).Magnitude = Mag(i);
    catalog(i).DateTime = datestr(dts(i),'yyyy/mm/dd HH:MM:SS.FFF');
    catalog(i).AUTHOR = 'IGN';
    catalog(i).location = Localizacin{i};
    catalog(i).intensity = Inten{i};
    catalog(i).ID = Evento(i);
end
