function [catalog] = import1comcatFile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [TIME,LATITUDE,LONGITUDE,DEPTH,MAG,MAGTYPE,NST,GAP,DMIN,RMS1,NET,ID,UPDATED,PLACE,TYPE1,HORIZONTALERROR,DEPTHERROR,MAGERROR,MAGNST,STATUS1,LOCATIONSOURCE,MAGSOURCE]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [TIME,LATITUDE,LONGITUDE,DEPTH,MAG,MAGTYPE,NST,GAP,DMIN,RMS1,NET,ID,UPDATED,PLACE,TYPE1,HORIZONTALERROR,DEPTHERROR,MAGERROR,MAGNST,STATUS1,LOCATIONSOURCE,MAGSOURCE]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms1,net,id,updated,place,type1,horizontalError,depthError,magError,magNst,status1,locationSource,magSource] = importfile('Comcat_Buldir.csv',2, 18281);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/03/29 14:11:50
catalog = [];

s = dir(filename);
if s.bytes == 0
    warning('catalog empty')
    return
end

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%q)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: text (%q)
%   column7: text (%q)
%	column8: text (%q)
%   column9: text (%q)
%	column10: double (%f)
%   column11: text (%q)
%	column12: text (%q)
%   column13: text (%q)
%	column14: text (%q)
%   column15: text (%q)
%	column16: text (%q)
%   column17: double (%f)
%	column18: text (%q)
%   column19: double (%f)
%	column20: text (%q)
%   column21: text (%q)
%	column22: text (%q)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%f%f%f%f%q%q%q%q%f%q%q%q%q%q%q%f%q%f%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
if sum(~cellfun(@isempty,dataArray))~=0
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end
else
    warning('No events in comcat File')
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
time = dataArray{:, 1};
latitude = dataArray{:, 2};
longitude = dataArray{:, 3};
depth = dataArray{:, 4};
mag = dataArray{:, 5};
magType = dataArray{:, 6};
nst = dataArray{:, 7};
gap = dataArray{:, 8};
dmin = dataArray{:, 9};
rms1 = dataArray{:, 10};
net = dataArray{:, 11};
id = dataArray{:, 12};
updated = dataArray{:, 13};
place = dataArray{:, 14};
type1 = dataArray{:, 15};
horizontalError = dataArray{:, 16};
depthError = dataArray{:, 17};
magError = dataArray{:, 18};
magNst = dataArray{:, 19};
status1 = dataArray{:, 20};
locationSource = dataArray{:, 21};
magSource = dataArray{:, 22};

% catalog = struct('EVENTID',id,'DateTime',DTs,'Latitude',latitude,'Longitude',longitude,'Depth',depth,...
%     'AUTHOR',locationSource,'Catalog',net,'Magnitude',mag,'magType',magType,'MagAUTHOR',magSource,...
%     'nst',nst,'gap',gap,'dmin',dmin,'rms',rms1,'updated',updated,'place',place,'type',type1,...
%     'horizontalError',horizontalError,'depthError',depthError,'magError',magError,'magNst',magNst,'status',status1);

for i=1:size(time,1)

    catalog(i).EVENTID = char(id(i));
    catalog(i).DateTime = datestr(datenum(time(i),'yyyy/mm/dd HH:MM:SS.FFF'));
    catalog(i).Latitude = latitude(i);
    catalog(i).Longitude = longitude(i);
    catalog(i).Depth = depth(i);
    catalog(i).AUTHOR = char(locationSource(i));
    catalog(i).Catalog = char(net(i));
    catalog(i).Magnitude = mag(i);
    catalog(i).magType = char(magType(i));
    catalog(i).MagAUTHOR = char(magSource(i));
    catalog(i).nst = nst(i);
    catalog(i).gap = gap(i);
    catalog(i).dmin= dmin(i);
    catalog(i).rms= rms1(i);
    catalog(i).updated= updated(i);
    catalog(i).place= place(i);
    catalog(i).type= type1(i);
    catalog(i).horizontalError= horizontalError(i);
    catalog(i).depthError    = depthError(i);
    catalog(i).magError= magError(i);
    catalog(i).magNst= magNst(i);
    catalog(i).status= status1(i);
    
end
